version: '3.8'

volumes:
  cache:

services:
  app:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: golang

    build: 
      context: ..
      dockerfile: ./Dockerfile
      target: "devcontainer"
      args:
        - VARIANT=1.16
        # - NODE_VERSION=16
    # environment:
    #   VARIANT: 1.16
    #   NODE_VERSION: 16
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      # Mount the ssh folder to authenticate with github
      # - $HOME/.ssh/:/home/vscode/.ssh
      - $HOME/.ssh/:/home/golang/.ssh
      - cache:/go